# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mỹ Phẩm Maeux
email: trang.van@dwork.vn
description: Chuyên bán kem dầu ngựa dưỡng ẩm đến từ đảo Jeju.
  Không còn lo khô và nhờn da mỗi khi mùa đông đến nữa
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://myphammaeux.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap